version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibe-fanalyze-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - mysql
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6
    container_name: vibe-fanalyze-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  mysql:
    image: mysql:8
    container_name: vibe-fanalyze-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: vibe_fanalyze
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mongo_data:
  mysql_data: /var/lib/mysql
  ./mysql/init.sql: /docker-entrypoint-initdb.d/init.sql

